import Config

# Configure your database
config :homelab, Homelab.Repo,
  username: "homelab",
  password: "homelab",
  hostname: "localhost",
  port: 5433,
  database: "homelab_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Oban runs on a dedicated Postgres instance (see docker-compose.yml: oban-postgres).
config :homelab, Homelab.ObanRepo,
  username: "homelab",
  password: "homelab",
  hostname: "localhost",
  port: 5434,
  database: "homelab_oban_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :homelab, HomelabWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "+L+IE0bozZ618F25V9S0mejxN3sznTW45DjIWwk0qJ+lW+DcfR1JIfFmE8rvFMo7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:homelab, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:homelab, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :homelab, HomelabWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/homelab_web/router\.ex$",
      ~r"lib/homelab_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# NOTE: :orchestrator is deliberately NOT pinned here.
#
# It used to be pinned to DockerEngine "because dev has no Swarm" — but that made the
# environment a compile-time fact you had to maintain, and `Config.active_driver/2`
# reads app env BEFORE Settings, so the pin also silently defeated the Settings
# dropdown and made every orchestrator-conditional code path (Traefik's provider label,
# the Swarm cluster panel) render its Engine branch on a Swarm host.
#
# It is unnecessary: `Config.orchestrator/0` falls through to `inferred_orchestrator/0`,
# which asks the daemon whether it is in Swarm mode. A laptop daemon isn't, so dev gets
# DockerEngine on its own; kratos is, so prod gets DockerSwarm. Nothing to edit, nothing
# to keep in sync across branches.
#
# (config/test.exs still sets it, on purpose — that is how the Mox orchestrator is
# injected, and tests must never reach a real daemon to find out what they are.)

# Enable dev routes for dashboard and mailbox
config :homelab, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
