import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :homelab, HomelabWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled by the reverse proxy (Traefik) provisioned during setup.
# Uncomment below if the app is exposed directly:
# config :homelab, HomelabWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   exclude: [hosts: ["localhost", "127.0.0.1"]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Expose Prometheus metrics on this port (scraped over the internal Docker
# network by your existing Prometheus). See HomelabWeb.Telemetry.
config :homelab, prometheus_exporter_port: 9568

# Build-time Sentry settings; the DSN itself is supplied at runtime so the
# integration stays inert unless SENTRY_DSN is set. See config/runtime.exs.
config :sentry,
  enable_source_code_context: false,
  tags: %{app: "homelab-in-a-box"}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
